# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerprofile',
            name='photography_type',
            field=models.CharField(choices=[('N', 'Nature Photography'), ('S', 'Sports/Action Photography'), ('F', 'Family/Maternity'), ('E', 'Event/Wedding Photography'), ('A', 'Architectural Photography')], default='', max_length=1),
        ),
    ]
