# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 18:53
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_imagerprofile_photography_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='imagerprofile',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
