# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 02:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imager_profile', '0004_auto_20160411_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerprofile',
            name='friends',
            field=models.ManyToManyField(related_name='friends_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='camera',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='photography_type',
            field=models.CharField(choices=[('N', 'Nature Photography'), ('S', 'Sports/Action Photography'), ('F', 'Family/Maternity'), ('E', 'Event/Wedding Photography'), ('A', 'Architectural Photography')], default='N', max_length=1),
        ),
    ]
